In [17]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [18]:
data = pd.read_csv('Data-Collisions.csv', low_memory=False)

In [19]:
data.head()

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,1,1307,1307,3502005,Matched,Intersection,37475.0,...,Wet,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,2,52200,52200,2607959,Matched,Block,NaN,...,Wet,Dark - Street Lights On,NaN,6354039.0,NaN,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,3,26700,26700,1482393,Matched,Block,NaN,...,Dry,Daylight,NaN,4323031.0,NaN,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,4,1144,1144,3503937,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,5,17700,17700,1807429,Matched,Intersection,34387.0,...,Wet,Daylight,NaN,4028032.0,NaN,10,Entering at angle,0,0,N

In [20]:
data.describe()

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,INTKEY,SEVERITYCODE.1,PERSONCOUNT,PEDCOUNT,PEDCYLCOUNT,VEHCOUNT,SDOT_COLCODE,SDOTCOLNUM,SEGLANEKEY,CROSSWALKKEY
count,194673.000000,189339.000000,189339.000000,194673.000000,194673.000000,194673.000000,65070.000000,194673.000000,194673.000000,194673.000000,194673.000000,194673.000000,194673.000000,1.149360e+05,194673.000000,1.946730e+05
mean,1.298901,-122.330518,47.619543,108479.364930,141091.456350,141298.811381,37558.450576,1.298901,2.444427,0.037139,0.028391,1.920780,13.867768,7.972521e+06,269.401114,9.782452e+03
std,0.457778,0.029976,0.056157,62649.722558,86634.402737,86986.542110,51745.990273,0.457778,1.345929,0.198150,0.167413,0.631047,6.868755,2.553533e+06,3315.776055,7.226926e+04
min,1.000000,-122.419091,47.495573,1.000000,1001.000000,1001.000000,23807.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.007024e+06,0.000000,0.000000e+00
25%,1.000000,-122.348673,47.575956,54267.000000,70383.000000,70383.000000,28667.000000,1.000000,2.000000,0.000000,0.000000,2.000000,11.000000,6.040015e+06,0.000000,0.000000e+00
50%,1.000000,-122.330224,47.615369,106912.000000,123363.000000,123363.000000,29973.000000,1.000000,2.000000,0.000000,0.000000,2.000000,13.000000,8.023022e+06,0.000000,0.000000e+00
75%,2.000000,-122.311937,47.663664,162272.000000,203319.000000,203459.000000,33973.000000,2.000000,3.000000,0.000000,0.000000,2.000000,14.000000,1.015501e+07,0.000000,0.000000e+00
max,2.000000,-122.238949,47.734142,219547.000000,331454.000000,332954.000000,757580.000000,2.000000,81.000000,6.000000,2.000000,12.000000,69.000000,1.307202e+07,525241.000000,5.239700e+06

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194673 entries, 0 to 194672
Data columns (total 38 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   SEVERITYCODE    194673 non-null  int64
 1   X               189339 non-null  float64
 2   Y               189339 non-null  float64
 3   OBJECTID        194673 non-null  int64
 4   INCKEY          194673 non-null  int64
 5   COLDETKEY       194673 non-null  int64
 6   REPORTNO        194673 non-null  object
 7   STATUS          194673 non-null  object
 8   ADDRTYPE        192747 non-null  object
 9   INTKEY          65070 non-null   float64
 10  LOCATION        191996 non-null  object
 11  EXCEPTRSNCODE   84811 non-null   object
 12  EXCEPTRSNDESC   5638 non-null    object
 13  SEVERITYCODE.1  194673 non-null  int64
 14  SEVERITYDESC    194673 non-null  object
 15  COLLISIONTYPE   189769 non-null  object
 16  PERSONCOUNT     194673 non-null  int64
 17  PEDCOUNT        194673 non-null  int64
 18  PEDCYLCOUNT     194673 non-null  int64
 19  VEHCOUNT        194673 non-null  int64
 20  INCDATE         194673 non-null  object
 21  INCDTTM         194673 non-null  object
 22  JUNCTIONTYPE    188344 non-null  object
 23  SDOT_COLCODE    194673 non-null  int64
 24  SDOT_COLDESC    194673 non-null  object
 25  INATTENTIONIND  29805 non-null   object
 26  UNDERINFL       189789 non-null  object
 27  WEATHER         189592 non-null  object
 28  ROADCOND        189661 non-null  object
 29  LIGHTCOND       189503 non-null  object
 30  PEDROWNOTGRNT   4667 non-null    object
 31  SDOTCOLNUM      114936 non-null  float64
 32  SPEEDING        9333 non-null    object
 33  ST_COLCODE      194655 non-null  object
 34  ST_COLDESC      189769 non-null  object
 35  SEGLANEKEY      194673 non-null  int64
 36  CROSSWALKKEY    194673 non-null  int64
 37  HITPARKEDCAR    194673 non-null  object
dtypes: float64(4), int64(12), object(22)
memory usage: 56.4+ MB

## Dealing with Missing Values and Selecting Relevant Features

In [22]:
#func to return the missing values for the features
def missingDataPerFeature(data) :
    missing_data = data.isnull().sum()
    missing_data_percentage = missing_data.apply(lambda x : x/data.shape[0]*100)
    return missing_data_percentage

In [23]:
data_ = missingDataPerFeature(data)
data_

SEVERITYCODE       0.000000
X                  2.739979
Y                  2.739979
OBJECTID           0.000000
INCKEY             0.000000
COLDETKEY          0.000000
REPORTNO           0.000000
STATUS             0.000000
ADDRTYPE           0.989351
INTKEY            66.574718
LOCATION           1.375126
EXCEPTRSNCODE     56.434123
EXCEPTRSNDESC     97.103861
SEVERITYCODE.1     0.000000
SEVERITYDESC       0.000000
COLLISIONTYPE      2.519096
PERSONCOUNT        0.000000
PEDCOUNT           0.000000
PEDCYLCOUNT        0.000000
VEHCOUNT           0.000000
INCDATE            0.000000
INCDTTM            0.000000
JUNCTIONTYPE       3.251093
SDOT_COLCODE       0.000000
SDOT_COLDESC       0.000000
INATTENTIONIND    84.689710
UNDERINFL          2.508822
WEATHER            2.610018
ROADCOND           2.574574
LIGHTCOND          2.655736
PEDROWNOTGRNT     97.602646
SDOTCOLNUM        40.959455
SPEEDING          95.205807
ST_COLCODE         0.009246
ST_COLDESC         2.519096
SEGLANEKEY         0.000000
CROSSWALKKEY       0.000000
HITPARKEDCAR       0.000000
dtype: float64

In [25]:
#dropping features that have more than 50% of data mising
cols_to_drop = data_[data_>50].index.to_list()
cols_to_drop

['INTKEY',
 'EXCEPTRSNCODE',
 'EXCEPTRSNDESC',
 'INATTENTIONIND',
 'PEDROWNOTGRNT',
 'SPEEDING']

In [26]:
data = data.drop(columns=cols_to_drop, axis=1)

In [27]:
data.head()

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,LOCATION,...,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,SDOTCOLNUM,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,1,1307,1307,3502005,Matched,Intersection,5TH AVE NE AND NE 103RD ST,...,N,Overcast,Wet,Daylight,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,2,52200,52200,2607959,Matched,Block,AURORA BR BETWEEN RAYE ST AND BRIDGE WAY N,...,0,Raining,Wet,Dark - Street Lights On,6354039.0,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,3,26700,26700,1482393,Matched,Block,4TH AVE BETWEEN SENECA ST AND UNIVERSITY ST,...,0,Overcast,Dry,Daylight,4323031.0,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,4,1144,1144,3503937,Matched,Block,2ND AVE BETWEEN MARION ST AND MADISON ST,...,N,Clear,Dry,Daylight,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,5,17700,17700,1807429,Matched,Intersection,SWIFT AVE S AND SWIFT AV OFF RP,...,0,Raining,Wet,Daylight,4028032.0,10,Entering at angle,0,0,N

In [28]:
"""
Identifying the features that are just used for the sake of reporting or marking
a particular row uniquely and won't play any significant role in the model development 
"""
for col in data.columns :
    print(f"{col} : {data[col].nunique()}")

SEVERITYCODE : 2
X : 23563
Y : 23839
OBJECTID : 194673
INCKEY : 194673
COLDETKEY : 194673
REPORTNO : 194670
STATUS : 2
ADDRTYPE : 3
LOCATION : 24102
SEVERITYCODE.1 : 2
SEVERITYDESC : 2
COLLISIONTYPE : 10
PERSONCOUNT : 47
PEDCOUNT : 7
PEDCYLCOUNT : 3
VEHCOUNT : 13
INCDATE : 5985
INCDTTM : 162058
JUNCTIONTYPE : 7
SDOT_COLCODE : 39
SDOT_COLDESC : 39
UNDERINFL : 4
WEATHER : 11
ROADCOND : 9
LIGHTCOND : 9
SDOTCOLNUM : 114932
ST_COLCODE : 63
ST_COLDESC : 62
SEGLANEKEY : 1955
CROSSWALKKEY : 2198
HITPARKEDCAR : 2

In [30]:
data.SEGLANEKEY.unique()

array([    0,  6855, 25242, ..., 11583, 10319, 45880], dtype=int64)

In [213]:
data = data.drop(columns=["OBJECTID", "INCKEY", "COLDETKEY", "REPORTNO"], axis=1)

In [214]:
data.head()

,SEVERITYCODE,X,Y,STATUS,ADDRTYPE,LOCATION,SEVERITYCODE.1,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,...,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,SDOTCOLNUM,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,Matched,Intersection,5TH AVE NE AND NE 103RD ST,2,Injury Collision,Angles,2,...,N,Overcast,Wet,Daylight,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,Matched,Block,AURORA BR BETWEEN RAYE ST AND BRIDGE WAY N,1,Property Damage Only Collision,Sideswipe,2,...,0,Raining,Wet,Dark - Street Lights On,6354039.0,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,Matched,Block,4TH AVE BETWEEN SENECA ST AND UNIVERSITY ST,1,Property Damage Only Collision,Parked Car,4,...,0,Overcast,Dry,Daylight,4323031.0,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,Matched,Block,2ND AVE BETWEEN MARION ST AND MADISON ST,1,Property Damage Only Collision,Other,3,...,N,Clear,Dry,Daylight,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,Matched,Intersection,SWIFT AVE S AND SWIFT AV OFF RP,2,Injury Collision,Angles,2,...,0,Raining,Wet,Daylight,4028032.0,10,Entering at angle,0,0,N

In [215]:
missingDataPerFeature(data)

SEVERITYCODE       0.000000
X                  2.739979
Y                  2.739979
STATUS             0.000000
ADDRTYPE           0.989351
LOCATION           1.375126
SEVERITYCODE.1     0.000000
SEVERITYDESC       0.000000
COLLISIONTYPE      2.519096
PERSONCOUNT        0.000000
PEDCOUNT           0.000000
PEDCYLCOUNT        0.000000
VEHCOUNT           0.000000
INCDATE            0.000000
INCDTTM            0.000000
JUNCTIONTYPE       3.251093
SDOT_COLCODE       0.000000
SDOT_COLDESC       0.000000
UNDERINFL          2.508822
WEATHER            2.610018
ROADCOND           2.574574
LIGHTCOND          2.655736
SDOTCOLNUM        40.959455
ST_COLCODE         0.009246
ST_COLDESC         2.519096
SEGLANEKEY         0.000000
CROSSWALKKEY       0.000000
HITPARKEDCAR       0.000000
dtype: float64

In [216]:
data.SDOTCOLNUM.nunique()

114932

In [217]:
data.SDOTCOLNUM.isnull().sum()

79737

In [218]:
data.SDOTCOLNUM.isnull().sum() + data.SDOTCOLNUM.nunique()

194669

In [219]:
data = data.drop(columns=["SDOTCOLNUM"], axis=1)

In [220]:
missingDataPerFeature(data)

SEVERITYCODE      0.000000
X                 2.739979
Y                 2.739979
STATUS            0.000000
ADDRTYPE          0.989351
LOCATION          1.375126
SEVERITYCODE.1    0.000000
SEVERITYDESC      0.000000
COLLISIONTYPE     2.519096
PERSONCOUNT       0.000000
PEDCOUNT          0.000000
PEDCYLCOUNT       0.000000
VEHCOUNT          0.000000
INCDATE           0.000000
INCDTTM           0.000000
JUNCTIONTYPE      3.251093
SDOT_COLCODE      0.000000
SDOT_COLDESC      0.000000
UNDERINFL         2.508822
WEATHER           2.610018
ROADCOND          2.574574
LIGHTCOND         2.655736
ST_COLCODE        0.009246
ST_COLDESC        2.519096
SEGLANEKEY        0.000000
CROSSWALKKEY      0.000000
HITPARKEDCAR      0.000000
dtype: float64

In [221]:
data[data["SEVERITYCODE.1"] == data.SEVERITYCODE].shape

(194673, 27)

In [222]:
data = data.drop(columns=["SEVERITYCODE.1"],axis=1)

In [223]:
data.head()

,SEVERITYCODE,X,Y,STATUS,ADDRTYPE,LOCATION,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,...,SDOT_COLDESC,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,Matched,Intersection,5TH AVE NE AND NE 103RD ST,Injury Collision,Angles,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",N,Overcast,Wet,Daylight,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,Matched,Block,AURORA BR BETWEEN RAYE ST AND BRIDGE WAY N,Property Damage Only Collision,Sideswipe,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, LEFT SIDE ...",0,Raining,Wet,Dark - Street Lights On,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,Matched,Block,4TH AVE BETWEEN SENECA ST AND UNIVERSITY ST,Property Damage Only Collision,Parked Car,4,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",0,Overcast,Dry,Daylight,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,Matched,Block,2ND AVE BETWEEN MARION ST AND MADISON ST,Property Damage Only Collision,Other,3,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",N,Clear,Dry,Daylight,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,Matched,Intersection,SWIFT AVE S AND SWIFT AV OFF RP,Injury Collision,Angles,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",0,Raining,Wet,Daylight,10,Entering at angle,0,0,N

In [228]:
data = data.dropna()
data.to_csv("no-missing-data.csv",index=False)

In [225]:
missingDataPerFeature(data)

SEVERITYCODE     0.0
X                0.0
Y                0.0
STATUS           0.0
ADDRTYPE         0.0
LOCATION         0.0
SEVERITYDESC     0.0
COLLISIONTYPE    0.0
PERSONCOUNT      0.0
PEDCOUNT         0.0
PEDCYLCOUNT      0.0
VEHCOUNT         0.0
INCDATE          0.0
INCDTTM          0.0
JUNCTIONTYPE     0.0
SDOT_COLCODE     0.0
SDOT_COLDESC     0.0
UNDERINFL        0.0
WEATHER          0.0
ROADCOND         0.0
LIGHTCOND        0.0
ST_COLCODE       0.0
ST_COLDESC       0.0
SEGLANEKEY       0.0
CROSSWALKKEY     0.0
HITPARKEDCAR     0.0
dtype: float64

In [226]:
data[data.COLLISIONTYPE.isnull()][["COLLISIONTYPE","SEVERITYDESC"]]

Empty DataFrame
Columns: [COLLISIONTYPE, SEVERITYDESC]
Index: []

In [227]:
sample_data = data[["COLLISIONTYPE","SEVERITYDESC","SDOT_COLDESC"]].sample(50)
sample_data.head()

,COLLISIONTYPE,SEVERITYDESC,SDOT_COLDESC
100355,Parked Car,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END"
154026,Other,Property Damage Only Collision,MOTOR VEHICLE STRUCK OBJECT IN ROAD
149701,Sideswipe,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
74472,Rear Ended,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END"
61930,Parked Car,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END"

In [48]:
sample_data.SDOT_COLDESC.iloc[2]

'MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END AT ANGLE'

In [49]:
data.COLLISIONTYPE.unique()

array(['Angles', 'Sideswipe', 'Parked Car', 'Other', 'Cycles',
       'Rear Ended', 'Head On', nan, 'Left Turn', 'Pedestrian',
       'Right Turn'], dtype=object)

In [34]:
data.shape

(189339, 26)

In [35]:
data.dropna().shape

(180067, 26)

In [36]:
# data = data.dropna()

In [37]:
data.head()

,SEVERITYCODE,X,Y,STATUS,ADDRTYPE,LOCATION,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,...,SDOT_COLDESC,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,Matched,Intersection,5TH AVE NE AND NE 103RD ST,Injury Collision,Angles,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",N,Overcast,Wet,Daylight,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,Matched,Block,AURORA BR BETWEEN RAYE ST AND BRIDGE WAY N,Property Damage Only Collision,Sideswipe,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, LEFT SIDE ...",0,Raining,Wet,Dark - Street Lights On,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,Matched,Block,4TH AVE BETWEEN SENECA ST AND UNIVERSITY ST,Property Damage Only Collision,Parked Car,4,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",0,Overcast,Dry,Daylight,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,Matched,Block,2ND AVE BETWEEN MARION ST AND MADISON ST,Property Damage Only Collision,Other,3,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",N,Clear,Dry,Daylight,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,Matched,Intersection,SWIFT AVE S AND SWIFT AV OFF RP,Injury Collision,Angles,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",0,Raining,Wet,Daylight,10,Entering at angle,0,0,N

In [51]:
data[data.COLLISIONTYPE =="Angles"][["COLLISIONTYPE","SEVERITYDESC","SDOT_COLDESC"]]

,COLLISIONTYPE,SEVERITYDESC,SDOT_COLDESC
0,Angles,Injury Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
4,Angles,Injury Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
5,Angles,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
6,Angles,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
9,Angles,Injury Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
...,...,...,...
194648,Angles,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
194663,Angles,Injury Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
194664,Angles,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
194665,Angles,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."
194666,Angles,Injury Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ..."

In [180]:
missingDataPerFeature(data.dropna(subset=["COLLISIONTYPE","JUNCTIONTYPE","UNDERINFL"]))

SEVERITYCODE     0.000000
X                0.000000
Y                0.000000
STATUS           0.000000
ADDRTYPE         0.000000
LOCATION         0.000000
SEVERITYDESC     0.000000
COLLISIONTYPE    0.000000
PERSONCOUNT      0.000000
PEDCOUNT         0.000000
PEDCYLCOUNT      0.000000
VEHCOUNT         0.000000
INCDATE          0.000000
INCDTTM          0.000000
JUNCTIONTYPE     0.000000
SDOT_COLCODE     0.000000
SDOT_COLDESC     0.000000
UNDERINFL        0.000000
WEATHER          0.099736
ROADCOND         0.063720
LIGHTCOND        0.141847
ST_COLCODE       0.000000
ST_COLDESC       0.000000
SEGLANEKEY       0.000000
CROSSWALKKEY     0.000000
HITPARKEDCAR     0.000000
dtype: float64

In [181]:
data_ =data.dropna(subset=["COLLISIONTYPE","JUNCTIONTYPE","UNDERINFL"])

In [192]:
data_[data_.WEATHER.isnull()]

,SEVERITYCODE,X,Y,STATUS,ADDRTYPE,LOCATION,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,...,SDOT_COLDESC,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
486,1,-122.362241,47.557463,Matched,Block,SW HUDSON ST BETWEEN PUGET BLVD SW AND DELRIDG...,Property Damage Only Collision,Parked Car,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",N,NaN,Unknown,Unknown,32,One parked--one moving,0,0,Y
490,1,-122.379976,47.676852,Matched,Block,18TH AVE NW BETWEEN NW 65TH ST AND NW 67TH ST,Property Damage Only Collision,Parked Car,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",0,NaN,NaN,NaN,19,One car entering parked position,0,0,N
1673,2,-122.352785,47.625443,Matched,Intersection,2ND AVE N AND ROY ST,Injury Collision,Pedestrian,2,1,...,MOTOR VEHCILE STRUCK PEDESTRIAN,N,NaN,NaN,NaN,0,Vehicle going straight hits pedestrian,0,622682,N
1922,1,-122.384744,47.669066,Matched,Block,22ND AVE NW BETWEEN NW MARKET ST AND NW 56TH ST,Property Damage Only Collision,Parked Car,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, RIGHT SIDE...",N,NaN,Dry,Daylight,32,One parked--one moving,0,0,N
2152,2,-122.339684,47.570555,Matched,Block,EAST MARGINAL WAY S BETWEEN S SPOKANE SR ST AN...,Injury Collision,Pedestrian,2,1,...,MOTOR VEHCILE STRUCK PEDESTRIAN,N,NaN,NaN,NaN,0,Vehicle going straight hits pedestrian,0,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193251,1,-122.284487,47.603308,Matched,Block,LAKE WASHINGTON BLVD BETWEEN LAKESIDE AVE AND ...,Property Damage Only Collision,Other,1,0,...,MOTOR VEHICLE RAN OFF ROAD - HIT FIXED OBJECT,N,NaN,Wet,Dark - Street Lights Off,50,Fixed object,0,0,N
193514,2,-122.317894,47.537088,Matched,Block,EAST MARGINAL WAY S BETWEEN ELLIS AVE S AND S ...,Injury Collision,Cycles,1,0,...,MOTOR VEHICLE RAN OFF ROAD - HIT FIXED OBJECT,N,NaN,Wet,Dusk,5,Vehicle Strikes Pedalcyclist,0,0,N
193749,1,-122.334195,47.591355,Matched,Block,1ST AVE S BETWEEN S ROYAL BROUGHAM WAY AND S A...,Property Damage Only Collision,Rear Ended,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",N,NaN,NaN,Dusk,14,From same direction - both going straight - on...,0,0,N
193824,1,-122.362884,47.560181,Matched,Block,DELRIDGE WAY SW BETWEEN SW ALASKA ST AND SW ED...,Property Damage Only Collision,Rear Ended,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",N,NaN,NaN,NaN,13,From same direction - both going straight - bo...,0,0,N
193955,1,-122.260801,47.518688,Matched,Block,WATERS AVE S BETWEEN S FLETCHER ST AND 58TH AVE S,Property Damage Only Collision,Parked Car,2,0,...,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",N,NaN,Dry,Daylight,32,One parked--one moving,0,0,N

In [173]:
data.ROADCOND.unique()

array(['Wet', 'Dry', nan, 'Unknown', 'Snow/Slush', 'Ice', 'Other',
       'Sand/Mud/Dirt', 'Standing Water', 'Oil'], dtype=object)

In [174]:
data.WEATHER.unique()

array(['Overcast', 'Raining', 'Clear', nan, 'Unknown', 'Other', 'Snowing',
       'Fog/Smog/Smoke', 'Sleet/Hail/Freezing Rain', 'Blowing Sand/Dirt',
       'Severe Crosswind', 'Partly Cloudy'], dtype=object)

0                        Daylight
1         Dark - Street Lights On
2                        Daylight
3                        Daylight
4                        Daylight
                   ...
194668                   Daylight
194669                   Daylight
194670                   Daylight
194671                       Dusk
194672                   Daylight
Name: LIGHTCOND, Length: 189339, dtype: object

In [178]:
data.INCDATE.sort_values()

5940      2004/01/01 00:00:00+00
13360     2004/01/01 00:00:00+00
14075     2004/01/01 00:00:00+00
3164      2004/01/01 00:00:00+00
3291      2004/01/01 00:00:00+00
                   ...
191912    2020/05/17 00:00:00+00
191908    2020/05/18 00:00:00+00
192328    2020/05/18 00:00:00+00
193070    2020/05/19 00:00:00+00
192030    2020/05/20 00:00:00+00
Name: INCDATE, Length: 189339, dtype: object

In [179]:
data.UNDERINFL

0         N
1         0
2         0
3         N
4         0
         ..
194668    N
194669    N
194670    N
194671    N
194672    N
Name: UNDERINFL, Length: 189339, dtype: object

In [52]:
final_data = data.dropna()

In [53]:
final_data.shape

(180067, 26)

In [55]:
data.shape

(189339, 26)

In [166]:
data[data.COLLISIONTYPE.isnull()][["COLLISIONTYPE","SEVERITYDESC","SDOT_COLDESC","SDOT_COLCODE"]]

,COLLISIONTYPE,SEVERITYDESC,SDOT_COLDESC,SDOT_COLCODE
15,NaN,Property Damage Only Collision,MOTOR VEHICLE STRUCK OBJECT IN ROAD,26
36,NaN,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",11
53,NaN,Injury Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",11
60,NaN,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",14
75,NaN,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",11
...,...,...,...,...
194620,NaN,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",14
194625,NaN,Property Damage Only Collision,MOTOR VEHICLE STRUCK OBJECT IN ROAD,26
194646,NaN,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",14
194654,NaN,Property Damage Only Collision,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...",11
194655,NaN,Injury Collision,MOTOR VEHCILE STRUCK PEDESTRIAN,24

In [60]:
data.COLLISIONTYPE.nunique()

10

In [61]:
data.SDOT_COLCODE.nunique()

39

In [70]:
data[data.COLLISIONTYPE=="Angles"]["SDOT_COLCODE"].value_counts()

11    32008
14     1987
0       155
16      150
15       43
26       33
18       21
28       16
24       12
13       10
51        8
29        7
31        4
25        4
12        1
34        1
Name: SDOT_COLCODE, dtype: int64

In [148]:
data_coll = data.groupby("COLLISIONTYPE")["SDOT_COLCODE"].value_counts().to_frame()
data_coll

                            SDOT_COLCODE
COLLISIONTYPE SDOT_COLCODE
Angles        11                   32008
              14                    1987
              0                      155
              16                     150
              15                      43
...                                  ...
Sideswipe     21                       2
              27                       2
              31                       1
              35                       1
              56                       1

[185 rows x 1 columns]

In [118]:
data_coll.rename(columns={"SDOT_COLCODE" : "S_CODE"}, inplace=True)

In [141]:
data.COLLISIONTYPE.unique()

array(['Angles', 'Sideswipe', 'Parked Car', 'Other', 'Cycles',
       'Rear Ended', 'Head On', nan, 'Left Turn', 'Pedestrian',
       'Right Turn'], dtype=object)

In [160]:
coll_type = {}
for ele in data_coll.index.to_list() :
    if ele[0] not in coll_type.keys() :
        coll_type[ele[0]] =ele[1]
    else:continue
coll_type

{'Angles': 11,
 'Cycles': 18,
 'Head On': 11,
 'Left Turn': 11,
 'Other': 28,
 'Parked Car': 11,
 'Pedestrian': 24,
 'Rear Ended': 14,
 'Right Turn': 11,
 'Sideswipe': 11}

In [151]:
coll_type

{}

In [163]:
b26b6917fd7e4a76b8f110125220506

NameError: name 'b26b6917fd7e4a76b8f110125220506' is not defined

In [164]:
!pip install wwo-hist

Collecting wwo-hist
  Downloading wwo_hist-0.0.7-py3-none-any.whl (4.6 kB)
Installing collected packages: wwo-hist
Successfully installed wwo-hist-0.0.7